version: '3'

services:
  api-cashflow-pg:
    image: bitnami/postgresql
    
    ports:
      - 5432:5432
    
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASS}
      - POSTGRESQL_DATABASE=${DB_NAME}